core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post-delete"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/comment/api/v1/urls.py
from .views import CommentViewSet
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("posts/comments", CommentViewSet, basename="comment"),

urlpatterns = router.urls

core/comment/urls.py
from django.urls import path, include
from . import views

app_name = "comment"

urlpatterns = [
    path(
        "post/<int:post_id>/comments/",
        views.CommentListView.as_view(),
        name="comment-list",
    ),
    path(
        "post/<int:post_id>/create/",
        views.CommentCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "comment/<int:post_id>/edit/<int:pk>/",
        views.CommentEditView.as_view(),
        name="comment-edit",
    ),
    path(
        "comment/<int:post_id>/delete/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    path("api/v1/", include("comment.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="This is a test api for Blog project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="amirali@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


def redirectToApp(request):
    return HttpResponseRedirect("/accounts/register")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirectToApp, name="index"),
    path("blog/", include("blog.urls")),
    path("comment/", include("comment.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/comment/models.py
from django.db import models
from django.contrib.auth import get_user_model
from blog.models import Post

# Create your models here.

# getting user model object
# User = get_user_model()


class Comment(models.Model):
    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"comment-author: {self.author.user.email} - post: {self.post}"

core/comment/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = [
            "content",
        ]

core/comment/api/v1/views.py
from rest_framework.permissions import IsAuthenticated
from .serializers import CommentSerializer
from comment.models import Comment
from django.contrib.auth import get_user_model
from rest_framework import viewsets
from rest_framework.exceptions import PermissionDenied


User = get_user_model()


class CommentViewSet(viewsets.ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer
    permission_classes = [IsAuthenticated]
    ordering_fields = ["created_date"]

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            raise PermissionDenied("You must be logged in to view your comments.")
        return super().get_queryset().filter(author=self.request.user.profile)

    def perform_create(self, serializer):
        if not self.request.user.is_authenticated:
            raise PermissionDenied("You must be logged in to create a comment.")
        serializer.save(author=self.request.user.profile)

core/comment/views.py
from django.shortcuts import render
from blog.models import Post
from .models import Comment
from .forms import CommentForm
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

# Create your views here.


class CommentListView(ListView):
    model = Comment
    context_object_name = "comments"

    def get_queryset(self):
        post_id = self.kwargs["post_id"]
        return Comment.objects.filter(post_id=post_id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(Post, pk=self.kwargs["post_id"])
        return context


class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        form.instance.post_id = self.kwargs["post_id"]
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "comment:comment-list", kwargs={"post_id": self.kwargs["post_id"]}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(Post, pk=self.kwargs["post_id"])
        return context


class CommentEditView(UpdateView):
    model = Comment
    form_class = CommentForm

    def get_success_url(self):
        return reverse(
            "comment:comment-list", kwargs={"post_id": self.kwargs["post_id"]}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(Post, pk=self.kwargs["post_id"])
        return context


class CommentDeleteView(DeleteView):
    model = Comment

    def get_success_url(self):
        return reverse(
            "comment:comment-list", kwargs={"post_id": self.kwargs["post_id"]}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post"] = get_object_or_404(Post, pk=self.kwargs["post_id"])
        return context

core/templates/comment/comment_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Delete Comment{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'comment:comment-list' post_id=post.id%}"><h5>Back</h5></a>
    </form>
{% endblock content %}

core/templates/comment/comment_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}create Post{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <div class="container py-4">
    <h2 class="fw-bold mb-4 text-center">create Comment</h2>
    <div class="row g-4">
        <div class="col-md-6 col-lg-4">
            <div class="card post-card h-100">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Save"> 
                </form>
                <a href="{% url 'comment:comment-list' post_id=post.id%}"><h5>Back</h5></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/comment/comment_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Comments Post {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    {% for comment in comments %}
        <div class="col-md-6 col-lg-4">
            <div class="card post-card h-100">
                <div class="card-body d-flex flex-column">
                    <h2>{{comment.author}}</h2>
                    <p class="card-text">{{ comment.content}}</p>
                    {% if comment.author.user == request.user %}
                    <a href="{%url 'comment:comment-edit' post_id=post.id pk=comment.id%}">
                        <h5>Edit</h5>
                    </a>
                    <a href="{%url 'comment:comment-delete' post_id=post.id pk=comment.id%}">
                        <h5>Delete</h5>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">No comments published yet.</p>
        {% endfor %}
        <a href="{%url 'comment:comment-create' post_id=post.id%}">
            <h5>Create Comment</h5>
        </a>
        <a href="{% url 'blog:post-list' %}"><h5>Back</h5></a>
{% endblock content %}