core/blog/api/v1/urls.py
from .views import BlogViewSet, CategoryModelViewSet
from rest_framework.routers import DefaultRouter

app_name = "api-v1"

router = DefaultRouter()
router.register("post", BlogViewSet, basename="post"),
router.register("category", CategoryModelViewSet, basename="category")

urlpatterns = router.urls

core/blog/urls.py
from django.urls import path, include
from . import views

app_name = "blog"

urlpatterns = [
    path("post/", views.PostListView.as_view(), name="post-list"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path("post/<int:pk>/delete/", views.PostDeleteView.as_view(), name="post-delete"),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/comment/urls.py
from django.urls import path, include
from . import views

app_name = "comment"

urlpatterns = [
    path(
        "post/<int:post_id>/comments/",
        views.CommentListView.as_view(),
        name="comment-list",
    ),
    path(
        "post/<int:post_id>/create/",
        views.CommentCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "comment/<int:post_id>/edit/<int:pk>/",
        views.CommentEditView.as_view(),
        name="comment-edit",
    ),
    path(
        "comment/<int:post_id>/delete/<int:pk>/",
        views.CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    path("api/v1/", include("comment.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponseRedirect
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Blog API",
        default_version="v1",
        description="This is a test api for Blog project",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="amirali@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


def redirectToApp(request):
    return HttpResponseRedirect("/accounts/register")


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", redirectToApp, name="index"),
    path("blog/", include("blog.urls")),
    path("comment/", include("comment.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

# getting user model object
# User = get_user_model()


class Post(models.Model):
    """
    this is a class to define posts for blog app
    """

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "status",
            "category",
            "published_date",
        ]

core/blog/api/v1/views.py
from rest_framework.permissions import IsAuthenticated
from .serializers import BlogSerializer, CategorySerializer
from blog.models import Post, Category
from django.contrib.auth import get_user_model
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.exceptions import PermissionDenied


User = get_user_model()


class BlogViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = BlogSerializer
    permission_classes = [IsAuthenticated]
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category"]
    search_fields = ["title"]
    ordering_fields = ["created_date"]

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            raise PermissionDenied("You must be logged in to view your posts.")
        return super().get_queryset().filter(author=self.request.user.profile)

    def perform_create(self, serializer):
        if not self.request.user.is_authenticated:
            raise PermissionDenied("You must be logged in to create a post.")
        serializer.save(author=self.request.user.profile)


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Post
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

# Create your views here.


@method_decorator(cache_page(60 * 20), name="dispatch")
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    context_object_name = "posts"
    paginate_by = 3
    ordering = "id"

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user.profile)


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    context_object_name = "post"


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


class PostEditView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post/"


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = "/blog/post/"

core/templates/blog/post_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Delete Post{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
    <a href="{% url 'blog:post-list' %}"><h5>Back</h5></a>
    </form>
{% endblock content %}

core/templates/blog/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Detail Post{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <div class="container py-5">
    <h2 class="fw-bold mb-4 text-center">Detail Post</h2>
    <div class="row g-4">
        <div class="col-md-6 col-lg-4">
            <div class="card post-card h-100">
                {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img-top post-image" alt="{{ post.title }}">
                {% endif %}
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.content}}</p>
                    
                    <div class="mt-auto">
                        <p class="post-meta">
                            Category: {{ post.category }} <br>
                            Author: {{ post.author}} <br>
                            Published: {{ post.published_date|date:"M d, Y" }}
                        </p>
                    </div>
                    <a href="{% url 'blog:post-list' %}"><h5>Back</h5></a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/blog/post_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}create Post{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <div class="container py-4">
    <h2 class="fw-bold mb-4 text-center">create Post</h2>
    <div class="row g-4">
        <div class="col-md-6 col-lg-4">
            <div class="card post-card h-100">
                <form method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" value="Save"> 
                </form>
                <a href="{% url 'blog:post-list' %}"><h5>Back</h5></a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}List Posts{% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
    <div class="container py-5">
    <h2 class="fw-bold mb-4 text-center">List Posts</h2>
    <div class="row g-4">
        {% for post in posts %}
        <div class="col-md-6 col-lg-4">
            <div class="card post-card h-100">
                {% if post.image %}
                <img src="{{ post.image.url }}" class="card-img-top post-image" alt="{{ post.title }}">
                {% endif %}
                <div class="card-body d-flex flex-column">
                    <a href="{% url 'blog:post-detail' pk=post.id %}"><h2>{{post.title}}</h2></a>
                    <p class="card-text">{{ post.content|truncatewords:20 }}</p>
                    <a href="{%url 'blog:post-edit' pk=post.id%}">
                        <h5>Edit</h5>
                    </a>
                    <a href="{%url 'blog:post-delete' pk=post.id%}">
                        <h5>Delete</h5>
                    </a>
                    <a href="{%url 'comment:comment-list' post_id=post.id%}">
                        <h5>Read comment</h5>
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">No posts published yet.</p>
        {% endfor %}
        <div>
            <a href="{%url 'blog:post-create'%}">
            <h5>Create Post</h5>
        </a>
        </div>
        <div class="pagination">
        <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
        </div>
        <form method="post" action="{% url 'logout' %}">
    {% csrf_token %}
    <button type="submit">Logout</button>
    </form>
    </div>
</div>
{% endblock content %}